FIELDS = [
    {
        "key": "anydesk",
        "prompt": "Укажите ваш AnyDesk ID или ссылку:",
        "type": "text",
        "bitrix_field": "UF_CRM_13_1764583097",
    },
    {
        "key": "address",
        "prompt": "Выберите адрес:",
        "type": "choice",
        "choices": ["Офис 1", "Офис 2", "Удалённо"],
        "bitrix_field": "UF_CRM_13_1764583138",
    },
    {
        "key": "description",
        "prompt": "Опишите ваше обращение:",
        "type": "text",
        "bitrix_field": "UF_CRM_13_1764583190",
    },
    {
        "key": "request_type",
        "prompt": "Выберите тип заявки:",
        "type": "choice",
        "choices": ["Инцидент", "Запрос на доработку", "Доступы"],
        "bitrix_field": "UF_CRM_13_1764583201",
    },
    {
        "key": "department",
        "prompt": "Выберите департамент:",
        "type": "choice",
        "choices": ["Бухгалтерия", "Продажи", "IT", "HR"],
        "bitrix_field": "UF_CRM_13_1764583242",
    },
    {
        "key": "bitrix_user_id",
        "prompt": "Укажите ID пользователя в Bitrix24, от которого подаётся заявка:",
        "type": "text",
        "bitrix_field": "ASSIGNED_BY_ID",
    },
    {
        "key": "city",
        "prompt": "Выберите город:",
        "type": "choice",
        "choices": ["Алматы", "Астана", "Шымкент"],
        "bitrix_field": "UF_CRM_13_1764583266",
    },
    {
        "key": "files",
        "prompt": "Пришлите файлы (скриншоты/документы). Когда закончите — напишите «готово».",
        "type": "files",
        "bitrix_field": "UF_CRM_13_1764583294",
    },
    {
        "key": "dev_comment",
        "prompt": "Комментарий по доработке (если нужен, иначе напишите «нет»):",
        "type": "text",
        "bitrix_field": "UF_CRM_13_1764583314",
    },
]